### ISSUE TITLE
Development to-do list

### ISSUE THREAD

**Issue by naruthk** [naruthk/mobile-uw-food-app#15]
# List of To-Do Items

## Database
- [ ] Adding more restaurants to the database

## Master Detail Screen
- [ ] (Optional) Add haptic feedback when the user adds

## Search Screen
- [x] After choosing an item from the given list, the user is redirected to the details page for that particular restaurant.
- [ ] When the Search bar is tapped, a view is shown that instantly retrieves the results according to what the user has typed.

## Favorites Screen
- [x] When the user taps on an item, take them to the MasterDetailVC
- [x] When the user logs out, the list of favorite items must be cleared out. At the moment, the data still remains there for some weird reasons.
- [x] Create an Empty View to show to the user if the Favorite screen has nothing to be presented.

## Account Screen
- [x] Design interface for the screen
- [ ] If a normal user logs in, he/she can change display name / email address / password. He/she will also be presented with a dialog to report some message to the admin.
- [x] If an admin logs in, he/she will be presented with a different screen that allows him/her to edit restaurants' data
