### ISSUE TITLE
User stories to-do list

### ISSUE THREAD

**Issue by naruthk** [naruthk/mobile-uw-food-app#7]
# Core User Story
## Guests: 
- [X] As a guest, I want to be able to view factual information regarding the dining locations
Users
- [x] As an user, I want to be able to submit comments regarding incorrect information of the dining locations to the administrator so that the administrator could correct them as soon as possible.
- [X] As an user, I want to be able to submit reviews regarding the dining locations so that other people can know more about how the environment was and how the food really taste
## Administrator
- [x] As an administrator, I want to be able to set factual information regarding the dining locations so that such information are displayed to the users and guests.
- [x] As an administrator, I want to be able to make changes to the factual information so that such information regarding the dining locations are always up to date.

# Optional User Story
## Guests & Users
- [X] As a guest/user, I want to be able to locate the dining locations so that I can get detailed directions to there from my current location or a desired location of my choice.
## Administrators
- [ ] As an administrator, I want to be able to view the reviews submitted by the users so that we could take actions to improve on customers’ satisfaction.

**Comment by thipokch** [comment]
Do a mail UI - As an user, I want to be able to submit comments regarding incorrect information of the dining locations to the administrator so that the administrator could correct them as soon as possible.

**Comment by thipokch** [comment]
Admin page - ME
